version: '2'
services:
    flask:
        build: ./api/
        ports:
            - "5000:5000"
        volumes:
            - ./api:/code
    vue:
        build: ./real-world-vue/
        ports:
            - "8080:8080"
        volumes:
            - ./real-world-vue/:/vue
