version: '2'
services:
    flask:
        build: ./api/
        ports:
            - "5000:5000"
        volumes:
            - ./api:/code
    vue:
        build: ./real-world-vue/
        ports:
            - "8080:8080"
        volumes:
            - ./real-world-vue/:/vue
    db:
        image: mysql:5.7
        ports:
            - 6603:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=mydb
            - MYSQL_USER=root
            - MYSQL_PASSWORD=secret
        volumes:
            - /storage/docker/mysql-datadir:/var/lib/mysql
