version: '2'
services:
    flask:
        build: ./flask_app/
        ports:
            - "5000:5000"
        volumes:
            - ./flask_app:/code
    vue:
        build: ./real-world-vue/
        ports:
            - "8081:8080"
        volumes:
            - ./real-world-vue/:/vue


