version: '2'
services:
    flask:
        build: ./api/
        ports:
            - "5000:5000"
        volumes:
            - ./api:/code
    vue:
        build: ./real-world-vue/
        ports:
            - "8080:8080"
        volumes:
            - ./real-world-vue/:/vue
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: testdb
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - /var/lib/mysql
